### PR TITLE
Recreate autopilot plan on new update

### LINKED ISSUE #816: Autopilot plan is not deleted after running a successful upgrade
### What happened?

Running successive upgrades on child clusters fails.

### Involved Areas

Cluster API integration

### What did you expect to happen?

1. Multiple upgrades of the child cluster should work.
2. Autopilot should keep history of the upgrade plans

### Steps to reproduce

Step 1. Apply manifests with new version definition. The change would trigger an upgrade command

k0smotron successfully runs the k0s upgrade operations.

Step 2 Apply again manifests with new version definition. The change would trigger an upgrade command

k0smotron fails with the following error:

```
2024-11-18T13:35:13Z    ERROR   Reconciler error        {"controller": "k0scontrolplane", "controllerGroup": "[controlplane.cluster.x-k8s.io](http://controlplane.cluster.x-k8s.io/)", "controllerKind": "K0sControlPlane", "K0sControlPlane": {"name":"child-02","namespace":"child-02"}, "namespace": "child-02", "name": "child-02", "reconcileID": "213dd124-c6ff-4db5-9687-5dbfb6b5d9e0", "error": "error creating autopilot plan: [plans.autopilot.k0sproject.io](http://plans.autopilot.k0sproject.io/) \"autopilot\" already exists"}
[sigs.k8s.io/controller-runtime/pkg/internal/controller](http://sigs.k8s.io/controller-runtime/pkg/internal/controller).(*Controller).reconcileHandler
        /go/pkg/mod/[sigs.k8s.io/controller-runtime@v0.16.5/pkg/internal/controller/controller.go:329](http://sigs.k8s.io/controller-runtime@v0.16.5/pkg/internal/controller/controller.go:329)
[sigs.k8s.io/controller-runtime/pkg/internal/controller](http://sigs.k8s.io/controller-runtime/pkg/internal/controller).(*Controller).processNextWorkItem
        /go/pkg/mod/[sigs.k8s.io/controller-runtime@v0.16.5/pkg/internal/controller/controller.go:266](http://sigs.k8s.io/controller-runtime@v0.16.5/pkg/internal/controller/controller.go:266)
[sigs.k8s.io/controller-runtime/pkg/internal/controller](http://sigs.k8s.io/controller-runtime/pkg/internal/controller).(*Controller).Start.func2.2
        /go/pkg/mod/[sigs.k8s.io/controller-runtime@v0.16.5/pkg/internal/controller/controller.go:227](http://sigs.k8s.io/controller-runtime@v0.16.5/pkg/internal/controller/controller.go:227)
``` 

As Autopilot cannot handle two plans with the same name, the upgrade operation fails.

Knowing this limitation of Autopilot, k0smotron should create unique named upgrade plans with unique IDs. This is important to keep the plans history for audit purposes. 

### k0smotron version

1.2.0

### k0s version

*

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by makhov**
Fixes #816

### CODE REVIEW

File: internal/controller/controlplane/helper.go [hunk 1]
```diff
@@ -277,45 +278,37 @@ func (c *K0sController) createAutopilotPlan(ctx context.Context, kcp *cpv1beta1.
...
-							}
-						}
-					}
-				}
-			}]
-		}
-	}`)
-
-	return clientset.RESTClient().Post().
+apiVersion: autopilot.k0sproject.io/v1beta2
```
Comment (makhov) [inline internal/controller/controlplane/helper.go:281]: Switching to YAML since `Patch(types.ApplyPatchType)` sets content-type header to `application/apply-patch+yaml`

File: internal/controller/controlplane/helper.go [hunk 2]
```diff
@@ -344,6 +345,28 @@ func (c *K0sController) createAutopilotPlan(ctx context.Context, kcp *cpv1beta1.
...
+		return fmt.Errorf("error getting autopilot plan's state: %w", err)
+	}
+	if found {
+		if state == "Schedulable" || state == "SchedulableWait" {
+			// autopilot is already running
+			return nil
+		}
+	}
+
+	err = clientset.RESTClient().Delete().AbsPath("/apis/autopilot.k0sproject.io/v1beta2/plans/autopilot").Do(ctx).Error()
```
Comment (apedriza) [inline internal/controller/controlplane/helper.go:365]: do we need to delete autopilot plan if we are using PATCH?

Comment (makhov) [reply internal/controller/controlplane/helper.go:364]: Unfortunately, yes. Autopilot behaves badly if we update the existing plan. So I got rid of patching and returned the previous POST implementation

**Review by apedriza — APPROVED** [review]
lgtm
