### PR TITLE
Fix ssh provisioner for sudo execs

### LINKED ISSUE #964: Remote machine provisioning does not work with non root user and useSudo: true
### What happened?

While deploying the remote cluster using K0rdent the RemoteMachine provisioning does not work with `useSudo: true` and `user: ubuntu` with the following status:
```
  status:
    failureMessage: 'failed to run command: command failed: client exec: ssh session
      wait: Process exited with status 2'
    failureReason: ProvisionFailed
```

My RemoteMachine specs:
```
  spec:
    address: 10.130.0.155
    port: 22
    sshKeyRef:
      name: remote-ssh-key
    useSudo: true
    user: ubuntu
---
  spec:
    address: 10.130.0.238
    port: 22
    sshKeyRef:
      name: remote-ssh-key
    useSudo: true
    user: ubuntu
```

I have two openstack instances (vms are accessible by ssh, ubuntu user has sudo capabilities) and I'm using those machines to deploy the Remote cluster using k0smotron. 

The control plane components were successfully provisioned but worker machines can't.

The infrastructure provider is failing:
```
2025-03-20T08:43:29Z	INFO	uploaded file	{"controller": "remotemachine", "controllerGroup": "infrastructure.cluster.x-k8s.io", "controllerKind": "RemoteMachine", "RemoteMachine": {"name":"remote-ekaz-1","namespace":"kcm-system"}, "namespace": "kcm-system", "name": "remote-ekaz-1", "reconcileID": "3d7c9fae-10e7-4b7f-886a-7a419ebdeb79", "remotemachine": {"name":"remote-ekaz-1","namespace":"kcm-system"}, "machine": "remote-ekaz-1", "path": "/etc/k0s.token", "permissions": 420}
DEBUG [ssh] 10.130.0.238:22: executing `curl -sSfL https://get.k0s.sh | K0S_VERSION=v1.31.5+k0s.0 sh`
2025-03-20T08:43:29Z	ERROR	failed to run command	{"controller": "remotemachine", "controllerGroup": "infrastructure.cluster.x-k8s.io", "controllerKind": "RemoteMachine", "RemoteMachine": {"name":"remote-ekaz-1","namespace":"kcm-system"}, "namespace": "kcm-system", "name": "remote-ekaz-1", "reconcileID": "3d7c9fae-10e7-4b7f-886a-7a419ebdeb79", "remotemachine": {"name":"remote-ekaz-1","namespace":"kcm-system"}, "machine": "remote-ekaz-1", "output": "Downloading k0s from URL: https://github.com/k0sproject/k0s/releases/download/v1.31.5+k0s.0/k0s-v1.31.5+k0s.0-amd64", "error": "command failed: client exec: ssh session wait: Process exited with status 2"}
```

When I manually run the download k0s command on my VM, it obviously fails without sudo:
```
ubuntu@ekaz-1:~$ curl -sSfL https://get.k0s.sh | K0S_VERSION=v1.31.5+k0s.0 sh
Downloading k0s from URL: https://github.com/k0sproject/k0s/releases/download/v1.31.5+k0s.0/k0s-v1.31.5+k0s.0-amd64
sh: 51: cannot create /usr/local/bin/k0s: Permission denied
ubuntu@ekaz-1:~$ echo $?
2
```

Same, when adding sudo to the curl command:
```
ubuntu@ekaz-1:~$ sudo curl -sSfL https://get.k0s.sh | K0S_VERSION=v1.31.5+k0s.0 sh
Downloading k0s from URL: https://github.com/k0sproject/k0s/releases/download/v1.31.5+k0s.0/k0s-v1.31.5+k0s.0-amd64
sh: 51: cannot create /usr/local/bin/k0s: Permission denied
ubuntu@ekaz-1:~$ echo $?
2
```

While debugging I modified the bootstrap script and manually added sudo to both curl and sh parts and the provisioning proceeded but failed on the next step of installing k0s worker.

The remote machines' provisioning works without issues if I'm using `user:root` (using the same VMs).

<details>
  <summary>Cluster objects</summary>
```
apiVersion: v1
items:
- apiVersion: cluster.x-k8s.io/v1beta1
  kind: Cluster
  metadata:
    annotations:
      k0sproject.io/cluster-id: kube-system:7b835b47-b3f9-406b-bf0f-f30bafc906d2
      meta.helm.sh/release-name: remote-ekaz
      meta.helm.sh/release-namespace: kcm-system
    creationTimestamp: "2025-03-20T08:38:06Z"
    finalizers:
    - cluster.cluster.x-k8s.io
    generation: 2
    labels:
      app.kubernetes.io/managed-by: Helm
      helm.toolkit.fluxcd.io/name: remote-ekaz
      helm.toolkit.fluxcd.io/namespace: kcm-system
      k0rdent.mirantis.com/component: kcm
    name: remote-ekaz
    namespace: kcm-system
    resourceVersion: "603898"
    uid: e05d1efa-9487-4acd-960e-7cab8a6f01f8
  spec:
    clusterNetwork:
      pods:
        cidrBlocks:
        - 10.244.0.0/16
      services:
        cidrBlocks:
        - 10.96.0.0/12
    controlPlaneEndpoint:
      host: 172.18.0.2
      port: 30443
    controlPlaneRef:
      apiVersion: controlplane.cluster.x-k8s.io/v1beta1
      kind: K0smotronControlPlane
      name: remote-ekaz-cp
      namespace: kcm-system
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: RemoteCluster
      name: remote-ekaz
      namespace: kcm-system
  status:
    conditions:
    - lastTransitionTime: "2025-03-20T08:41:20Z"
      status: "True"
      type: Ready
    - lastTransitionTime: "2025-03-20T08:38:09Z"
      status: "True"
      type: ControlPlaneInitialized
    - lastTransitionTime: "2025-03-20T08:41:20Z"
      status: "True"
      type: ControlPlaneReady
    - lastTransitionTime: "2025-03-20T08:38:06Z"
      status: "True"
      type: InfrastructureReady
    controlPlaneReady: true
    infrastructureReady: true
    observedGeneration: 2
    phase: Provisioned
    v1beta2:
      conditions:
      - lastTransitionTime: "2025-03-20T08:41:20Z"
        message: ""
        observedGeneration: 2
        reason: Available
        status: "True"
        type: Available
      - lastTransitionTime: "2025-03-20T08:39:39Z"
        message: ""
        observedGeneration: 2
        reason: ProbeSucceeded
        status: "True"
        type: RemoteConnectionProbe
      - lastTransitionTime: "2025-03-20T08:38:06Z"
        message: ""
        observedGeneration: 2
        reason: Ready
        status: "True"
        type: InfrastructureReady
      - lastTransitionTime: "2025-03-20T08:38:09Z"
        message: ""
        observedGeneration: 2
        reason: Initialized
        status: "True"
        type: ControlPlaneInitialized
      - lastTransitionTime: "2025-03-20T08:41:20Z"
        message: ""
        observedGeneration: 2
        reason: Available
        status: "True"
        type: ControlPlaneAvailable
      - lastTransitionTime: "2025-03-20T08:38:06Z"
        message: ""
        observedGeneration: 2
        reason: NoWorkers
        status: "True"
        type: WorkersAvailable
      - lastTransitionTime: "2025-03-20T08:38:06Z"
        message: Please check controller logs for errors
        observedGeneration: 2
        reason: InternalError
        status: Unknown
        type: RollingOut
      - lastTransitionTime: "2025-03-20T08:38:06Z"
        message: ""
        observedGeneration: 2
        reason: NotRemediating
        status: "False"
        type: Remediating
      - lastTransitionTime: "2025-03-20T08:38:06Z"
        message: Please check controller logs for errors
        observedGeneration: 2
        reason: InternalError
        status: Unknown
        type: ScalingDown
      - lastTransitionTime: "2025-03-20T08:38:06Z"
        message: Please check controller logs for errors
        observedGeneration: 2
        reason: InternalError
        status: Unknown
        type: ScalingUp
      - lastTransitionTime: "2025-03-20T08:38:06Z"
        message: ""
        observedGeneration: 2
        reason: NoReplicas
        status: "True"
        type: ControlPlaneMachinesReady
      - lastTransitionTime: "2025-03-20T08:38:07Z"
        message: |-
          * Machines remote-ekaz-0, remote-ekaz-1:
            * InfrastructureReady: RemoteMachine status.ready is false
            * NodeHealthy: Waiting for RemoteMachine to report spec.providerID
        observedGeneration: 2
        reason: NotReady
        status: "False"
        type: WorkerMachinesReady
      - lastTransitionTime: "2025-03-20T08:38:06Z"
        message: ""
        observedGeneration: 2
        reason: NoReplicas
        status: "True"
        type: ControlPlaneMachinesUpToDate
      - lastTransitionTime: "2025-03-20T08:38:39Z"
        message: '* Machines remote-ekaz-0, remote-ekaz-1: Condition UpToDate not
          yet reported'
        observedGeneration: 2
        reason: UpToDateUnknown
        status: Unknown
        type: WorkerMachinesUpToDate
      - lastTransitionTime: "2025-03-20T08:38:06Z"
        message: ""
        observedGeneration: 2
        reason: NotPaused
        status: "False"
        type: Paused
      - lastTransitionTime: "2025-03-20T08:38:06Z"
        message: ""
        observedGeneration: 2
        reason: NotDeleting
        status: "False"
        type: Deleting
      controlPlane:
        desiredReplicas: 3
        readyReplicas: 3
        replicas: 3
      workers:
        desiredReplicas: 2
        replicas: 2
- apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
  kind: RemoteCluster
  metadata:
    annotations:
      meta.helm.sh/release-name: remote-ekaz
      meta.helm.sh/release-namespace: kcm-system
    creationTimestamp: "2025-03-20T08:38:06Z"
    generation: 2
    labels:
      app.kubernetes.io/managed-by: Helm
      cluster.x-k8s.io/cluster-name: remote-ekaz
      helm.toolkit.fluxcd.io/name: remote-ekaz
      helm.toolkit.fluxcd.io/namespace: kcm-system
    name: remote-ekaz
    namespace: kcm-system
    ownerReferences:
    - apiVersion: cluster.x-k8s.io/v1beta1
      blockOwnerDeletion: true
      controller: true
      kind: Cluster
      name: remote-ekaz
      uid: e05d1efa-9487-4acd-960e-7cab8a6f01f8
    resourceVersion: "601559"
    uid: 27846c39-85f6-495d-bc48-3d4591419f23
  spec:
    controlPlaneEndpoint:
      host: 172.18.0.2
      port: 30443
  status:
    ready: true
- apiVersion: cluster.x-k8s.io/v1beta1
  kind: Machine
  metadata:
    annotations:
      meta.helm.sh/release-name: remote-ekaz
      meta.helm.sh/release-namespace: kcm-system
    creationTimestamp: "2025-03-20T08:38:06Z"
    finalizers:
    - machine.cluster.x-k8s.io
    generation: 2
    labels:
      app.kubernetes.io/managed-by: Helm
      cluster.x-k8s.io/cluster-name: remote-ekaz
      helm.toolkit.fluxcd.io/name: remote-ekaz
      helm.toolkit.fluxcd.io/namespace: kcm-system
    name: remote-ekaz-0
    namespace: kcm-system
    ownerReferences:
    - apiVersion: cluster.x-k8s.io/v1beta1
      kind: Cluster
      name: remote-ekaz
      uid: e05d1efa-9487-4acd-960e-7cab8a6f01f8
    resourceVersion: "604299"
    uid: 2bbbe9b6-9863-4b07-a48a-675272e1ed17
  spec:
    bootstrap:
      configRef:
        apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
        kind: K0sWorkerConfig
        name: remote-ekaz-0
        namespace: kcm-system
      dataSecretName: remote-ekaz-0
    clusterName: remote-ekaz
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: RemoteMachine
      name: remote-ekaz-0
      namespace: kcm-system
    nodeDeletionTimeout: 10s
  status:
    bootstrapReady: true
    conditions:
    - lastTransitionTime: "2025-03-20T08:41:22Z"
      message: 1 of 2 completed
      reason: WaitingForInfrastructure
      severity: Info
      status: "False"
      type: Ready
    - lastTransitionTime: "2025-03-20T08:41:22Z"
      status: "True"
      type: BootstrapReady
    - lastTransitionTime: "2025-03-20T08:38:06Z"
      reason: WaitingForInfrastructure
      severity: Info
      status: "False"
      type: InfrastructureReady
    - lastTransitionTime: "2025-03-20T08:38:06Z"
      reason: WaitingForNodeRef
      severity: Info
      status: "False"
      type: NodeHealthy
    failureMessage: 'Failure detected from referenced resource infrastructure.cluster.x-k8s.io/v1beta1,
      Kind=RemoteMachine with name "remote-ekaz-0": failed to run command: command
      failed: client exec: ssh session wait: Process exited with status 2'
    failureReason: ProvisionFailed
    lastUpdated: "2025-03-20T08:42:37Z"
    observedGeneration: 2
    phase: Failed
    v1beta2:
      conditions:
      - lastTransitionTime: "2025-03-20T08:38:06Z"
        message: ""
        observedGeneration: 2
        reason: NotReady
        status: "False"
        type: Available
      - lastTransitionTime: "2025-03-20T08:38:06Z"
        message: |-
          * InfrastructureReady: RemoteMachine status.ready is false
          * NodeHealthy: Waiting for RemoteMachine to report spec.providerID
        observedGeneration: 2
        reason: NotReady
        status: "False"
        type: Ready
      - lastTransitionTime: "2025-03-20T08:41:22Z"
        message: ""
        observedGeneration: 2
        reason: Ready
        status: "True"
        type: BootstrapConfigReady
      - lastTransitionTime: "2025-03-20T08:38:06Z"
        message: RemoteMachine status.ready is false
        observedGeneration: 2
        reason: NotReady
        status: "False"
        type: InfrastructureReady
      - lastTransitionTime: "2025-03-20T08:38:06Z"
        message: Waiting for RemoteMachine to report spec.providerID
        observedGeneration: 2
        reason: InspectionFailed
        status: Unknown
        type: NodeHealthy
      - lastTransitionTime: "2025-03-20T08:38:06Z"
        message: Waiting for RemoteMachine to report spec.providerID
        observedGeneration: 2
        reason: InspectionFailed
        status: Unknown
        type: NodeReady
      - lastTransitionTime: "2025-03-20T08:38:06Z"
        message: ""
        observedGeneration: 2
        reason: NotPaused
        status: "False"
        type: Paused
      - lastTransitionTime: "2025-03-20T08:38:06Z"
        message: ""
        observedGeneration: 2
        reason: NotDeleting
        status: "False"
        type: Deleting
- apiVersion: cluster.x-k8s.io/v1beta1
  kind: Machine
  metadata:
    annotations:
      meta.helm.sh/release-name: remote-ekaz
      meta.helm.sh/release-namespace: kcm-system
    creationTimestamp: "2025-03-20T08:38:06Z"
    finalizers:
    - machine.cluster.x-k8s.io
    generation: 2
    labels:
      app.kubernetes.io/managed-by: Helm
      cluster.x-k8s.io/cluster-name: remote-ekaz
      helm.toolkit.fluxcd.io/name: remote-ekaz
      helm.toolkit.fluxcd.io/namespace: kcm-system
    name: remote-ekaz-1
    namespace: kcm-system
    ownerReferences:
    - apiVersion: cluster.x-k8s.io/v1beta1
      kind: Cluster
      name: remote-ekaz
      uid: e05d1efa-9487-4acd-960e-7cab8a6f01f8
    resourceVersion: "604304"
    uid: 1adc4101-90bc-49d0-9960-9fc215a0ccfa
  spec:
    bootstrap:
      configRef:
        apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
        kind: K0sWorkerConfig
        name: remote-ekaz-1
        namespace: kcm-system
      dataSecretName: remote-ekaz-1
    clusterName: remote-ekaz
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: RemoteMachine
      name: remote-ekaz-1
      namespace: kcm-system
    nodeDeletionTimeout: 10s
  status:
    bootstrapReady: true
    conditions:
    - lastTransitionTime: "2025-03-20T08:41:22Z"
      message: 1 of 2 completed
      reason: WaitingForInfrastructure
      severity: Info
      status: "False"
      type: Ready
    - lastTransitionTime: "2025-03-20T08:41:22Z"
      status: "True"
      type: BootstrapReady
    - lastTransitionTime: "2025-03-20T08:38:06Z"
      reason: WaitingForInfrastructure
      severity: Info
      status: "False"
      type: InfrastructureReady
    - lastTransitionTime: "2025-03-20T08:38:06Z"
      reason: WaitingForNodeRef
      severity: Info
      status: "False"
      type: NodeHealthy
    failureMessage: 'Failure detected from referenced resource infrastructure.cluster.x-k8s.io/v1beta1,
      Kind=RemoteMachine with name "remote-ekaz-1": failed to run command: command
      failed: client exec: ssh session wait: Process exited with status 2'
    failureReason: ProvisionFailed
    lastUpdated: "2025-03-20T08:42:38Z"
    observedGeneration: 2
    phase: Failed
    v1beta2:
      conditions:
      - lastTransitionTime: "2025-03-20T08:38:06Z"
        message: ""
        observedGeneration: 2
        reason: NotReady
        status: "False"
        type: Available
      - lastTransitionTime: "2025-03-20T08:38:06Z"
        message: |-
          * InfrastructureReady: RemoteMachine status.ready is false
          * NodeHealthy: Waiting for RemoteMachine to report spec.providerID
        observedGeneration: 2
        reason: NotReady
        status: "False"
        type: Ready
      - lastTransitionTime: "2025-03-20T08:41:22Z"
        message: ""
        observedGeneration: 2
        reason: Ready
        status: "True"
        type: BootstrapConfigReady
      - lastTransitionTime: "2025-03-20T08:38:06Z"
        message: RemoteMachine status.ready is false
        observedGeneration: 2
        reason: NotReady
        status: "False"
        type: InfrastructureReady
      - lastTransitionTime: "2025-03-20T08:38:06Z"
        message: Waiting for RemoteMachine to report spec.providerID
        observedGeneration: 2
        reason: InspectionFailed
        status: Unknown
        type: NodeHealthy
      - lastTransitionTime: "2025-03-20T08:38:06Z"
        message: Waiting for RemoteMachine to report spec.providerID
        observedGeneration: 2
        reason: InspectionFailed
        status: Unknown
        type: NodeReady
      - lastTransitionTime: "2025-03-20T08:38:06Z"
        message: ""
        observedGeneration: 2
        reason: NotPaused
        status: "False"
        type: Paused
      - lastTransitionTime: "2025-03-20T08:38:06Z"
        message: ""
        observedGeneration: 2
        reason: NotDeleting
        status: "False"
        type: Deleting
- apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
  kind: RemoteMachine
  metadata:
    annotations:
      meta.helm.sh/release-name: remote-ekaz
      meta.helm.sh/release-namespace: kcm-system
    creationTimestamp: "2025-03-20T08:38:06Z"
    generation: 1
    labels:
      app.kubernetes.io/managed-by: Helm
      cluster.x-k8s.io/cluster-name: remote-ekaz
      helm.toolkit.fluxcd.io/name: remote-ekaz
      helm.toolkit.fluxcd.io/namespace: kcm-system
    name: remote-ekaz-0
    namespace: kcm-system
    ownerReferences:
    - apiVersion: cluster.x-k8s.io/v1beta1
      blockOwnerDeletion: true
      controller: true
      kind: Machine
      name: remote-ekaz-0
      uid: 2bbbe9b6-9863-4b07-a48a-675272e1ed17
    resourceVersion: "604298"
    uid: dc098e15-b91b-4159-a0b8-564e22712a78
  spec:
    address: 10.130.0.155
    port: 22
    sshKeyRef:
      name: remote-ssh-key
    useSudo: true
    user: ubuntu
  status:
    failureMessage: 'failed to run command: command failed: client exec: ssh session
      wait: Process exited with status 2'
    failureReason: ProvisionFailed
- apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
  kind: RemoteMachine
  metadata:
    annotations:
      meta.helm.sh/release-name: remote-ekaz
      meta.helm.sh/release-namespace: kcm-system
    creationTimestamp: "2025-03-20T08:38:06Z"
    generation: 1
    labels:
      app.kubernetes.io/managed-by: Helm
      cluster.x-k8s.io/cluster-name: remote-ekaz
      helm.toolkit.fluxcd.io/name: remote-ekaz
      helm.toolkit.fluxcd.io/namespace: kcm-system
    name: remote-ekaz-1
    namespace: kcm-system
    ownerReferences:
    - apiVersion: cluster.x-k8s.io/v1beta1
      blockOwnerDeletion: true
      controller: true
      kind: Machine
      name: remote-ekaz-1
      uid: 1adc4101-90bc-49d0-9960-9fc215a0ccfa
    resourceVersion: "604303"
    uid: 391a973d-b697-4b75-9ad9-c6411532c9b5
  spec:
    address: 10.130.0.238
    port: 22
    sshKeyRef:
      name: remote-ssh-key
    useSudo: true
    user: ubuntu
  status:
    failureMessage: 'failed to run command: command failed: client exec: ssh session
      wait: Process exited with status 2'
    failureReason: ProvisionFailed
- apiVersion: controlplane.cluster.x-k8s.io/v1beta1
  kind: K0smotronControlPlane
  metadata:
    annotations:
      meta.helm.sh/release-name: remote-ekaz
      meta.helm.sh/release-namespace: kcm-system
    creationTimestamp: "2025-03-20T08:38:06Z"
    generation: 1
    labels:
      app.kubernetes.io/managed-by: Helm
      cluster.x-k8s.io/cluster-name: remote-ekaz
      helm.toolkit.fluxcd.io/name: remote-ekaz
      helm.toolkit.fluxcd.io/namespace: kcm-system
    name: remote-ekaz-cp
    namespace: kcm-system
    ownerReferences:
    - apiVersion: cluster.x-k8s.io/v1beta1
      blockOwnerDeletion: true
      controller: true
      kind: Cluster
      name: remote-ekaz
      uid: e05d1efa-9487-4acd-960e-7cab8a6f01f8
    resourceVersion: "603896"
    uid: f0e9a17c-d26d-4a75-9005-e627fb917848
  spec:
    etcd:
      autoDeletePVCs: false
      image: quay.io/k0sproject/etcd:v3.5.13
      persistence:
        size: 1Gi
    image: k0sproject/k0s
    k0sConfig:
      apiVersion: k0s.k0sproject.io/v1beta1
      kind: ClusterConfig
      metadata:
        name: k0s
      spec:
        extensions:
          helm: null
    persistence:
      autoDeletePVCs: false
      type: emptyDir
    replicas: 3
    service:
      apiPort: 30443
      konnectivityPort: 30132
      type: NodePort
    version: v1.31.5-k0s.0
  status:
    controlPlaneReady: true
    externalManagedControlPlane: true
    initialized: true
    ready: true
    readyReplicas: 3
    replicas: 3
    unavailableReplicas: 0
    updatedReplicas: 3
    version: v1.31.5-k0s.0
- apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
  kind: K0sWorkerConfig
  metadata:
    annotations:
      helm.sh/resource-policy: keep
      meta.helm.sh/release-name: remote-ekaz
      meta.helm.sh/release-namespace: kcm-system
    creationTimestamp: "2025-03-20T08:38:06Z"
    generation: 1
    labels:
      app.kubernetes.io/managed-by: Helm
      cluster.x-k8s.io/cluster-name: remote-ekaz
      helm.toolkit.fluxcd.io/name: remote-ekaz
      helm.toolkit.fluxcd.io/namespace: kcm-system
    name: remote-ekaz-0
    namespace: kcm-system
    ownerReferences:
    - apiVersion: cluster.x-k8s.io/v1beta1
      blockOwnerDeletion: true
      controller: true
      kind: Machine
      name: remote-ekaz-0
      uid: 2bbbe9b6-9863-4b07-a48a-675272e1ed17
    resourceVersion: "603517"
    uid: 8a4b2e6a-50f1-4ae7-8c0f-928cddea3e6f
  spec:
    useSystemHostname: false
    version: v1.31.5+k0s.0
  status:
    conditions:
    - lastTransitionTime: "2025-03-20T08:41:22Z"
      status: "True"
      type: Ready
    - lastTransitionTime: "2025-03-20T08:41:22Z"
      status: "True"
      type: DataSecretAvailable
    dataSecretName: remote-ekaz-0
    ready: true
- apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
  kind: K0sWorkerConfig
  metadata:
    annotations:
      helm.sh/resource-policy: keep
      meta.helm.sh/release-name: remote-ekaz
      meta.helm.sh/release-namespace: kcm-system
    creationTimestamp: "2025-03-20T08:38:06Z"
    generation: 1
    labels:
      app.kubernetes.io/managed-by: Helm
      cluster.x-k8s.io/cluster-name: remote-ekaz
      helm.toolkit.fluxcd.io/name: remote-ekaz
      helm.toolkit.fluxcd.io/namespace: kcm-system
    name: remote-ekaz-1
    namespace: kcm-system
    ownerReferences:
    - apiVersion: cluster.x-k8s.io/v1beta1
      blockOwnerDeletion: true
      controller: true
      kind: Machine
      name: remote-ekaz-1
      uid: 1adc4101-90bc-49d0-9960-9fc215a0ccfa
    resourceVersion: "603512"
    uid: a9e8089d-2fd6-470c-8fea-cf3fbe187909
  spec:
    useSystemHostname: false
    version: v1.31.5+k0s.0
  status:
    conditions:
    - lastTransitionTime: "2025-03-20T08:41:22Z"
      status: "True"
      type: Ready
    - lastTransitionTime: "2025-03-20T08:41:22Z"
      status: "True"
      type: DataSecretAvailable
    dataSecretName: remote-ekaz-1
    ready: true
kind: List
metadata:
  resourceVersion: ""
```
</details>

### Involved Areas

Cluster API integration

### What did you expect to happen?

Remote machines' provisioning works with `useSudo: true` and non root user.

### Steps to reproduce

1. Deploy k0smotron v1.4.2
2. Create the secret with SSH private key to access VMs
3. Create CAPI objects for the RemoteCluster provisioning. In RemoteMachines configure: `useSudo: true` and non-root user (examples can be found in the issue description) or https://docs.k0smotron.io/stable/capi-remote/#using-remotemachines 

### k0smotron version

v1.4.2

### k0s version

v1.31.5

### Anything else we need to know?

Provider logs:
[infra-logs.txt](https://github.com/user-attachments/files/19362227/infra-logs.txt)
[bootstrap-logs.txt](https://github.com/user-attachments/files/19362248/bootstrap-logs.txt)
[cp-logs.txt](https://github.com/user-attachments/files/19362247/cp-logs.txt)

### PR DESCRIPTION
**Pull request by apedriza**
fix #964

`useSudo` option was only implemented for job provisioned. In this changes, I bump `rig` and use [Sudo fn](https://pkg.go.dev/github.com/k0sproject/rig/v2@v2.0.0-alpha.3#Client.Sudo) wrapper for ssh commands when `useSudo = true` is set.

### CODE REVIEW

File: internal/controller/controlplane/k0smotron_controlplane_controller.go [hunk 1]
```diff
@@ -374,6 +374,16 @@ func isClusterSpecSynced(kmcSpec, kcpSpec kapi.ClusterSpec) (bool, error) {
 	// certificate references based on the original Cluster definition.
 	overridenKmcSpec.CertificateRefs = kmcSpec.CertificateRefs
 
+	// K0smotron Cluster controller will add additional SANs, such as those related to the externaladdress or to the service that exposes the controlplanes.
+	// Therefore, we explicitly reset the SANs references based on the original Cluster definition.
+	kmcSans, found, err := unstructured.NestedSlice(kmcSpec.K0sConfig.Object, "spec", "api", "sans")
```
Comment (apedriza) [inline internal/controller/controlplane/k0smotron_controlplane_controller.go]: I found a bug when SANs are set in the k0smotroncontrolplane spec. I wonder if we could handle all this sync check between the k0smotroncontrolplane and k0smotron cluster in a different way, where we don't take into account which parts can be modified by the k0smotron cluster controller. Maybe we still missed some condition in this logic, but I cannot think of another overrides right now.

**Review by makhov — APPROVED** [review]
